"""eventpost table

Revision ID: fb25f6f10561
Revises: 57e664c5fefe
Create Date: 2025-09-03 18:57:00.291047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb25f6f10561'
down_revision = '57e664c5fefe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_title', sa.String(length=100), nullable=False),
    sa.Column('event_location', sa.String(length=50), nullable=False),
    sa.Column('event_description', sa.String(length=500), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_post_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_post_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_password_hash'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_password_hash'), ['password_hash'], unique=1)

    with op.batch_alter_table('event_post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_post_user_id'))
        batch_op.drop_index(batch_op.f('ix_event_post_event_date'))

    op.drop_table('event_post')
    # ### end Alembic commands ###
