"""empty message

Revision ID: fce4ff96e602
Revises: fb25f6f10561
Create Date: 2025-09-04 00:40:56.084739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fce4ff96e602'
down_revision = 'fb25f6f10561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ammount', sa.String(length=20), nullable=False),
    sa.Column('donation_time', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_donations_ammount'), ['ammount'], unique=False)
        batch_op.create_index(batch_op.f('ix_donations_donation_time'), ['donation_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_donations_user_id'), ['user_id'], unique=False)

    op.create_table('job_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=100), nullable=False),
    sa.Column('job_location', sa.String(length=50), nullable=False),
    sa.Column('job_description', sa.String(length=500), nullable=False),
    sa.Column('last_apply_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_post_last_apply_date'), ['last_apply_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_post_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('branch', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('location', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('passout_year', sa.String(length=4), nullable=False))
        batch_op.create_index(batch_op.f('ix_user_branch'), ['branch'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_passout_year'), ['passout_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_phone_number'), ['phone_number'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_phone_number'))
        batch_op.drop_index(batch_op.f('ix_user_passout_year'))
        batch_op.drop_index(batch_op.f('ix_user_location'))
        batch_op.drop_index(batch_op.f('ix_user_branch'))
        batch_op.drop_column('passout_year')
        batch_op.drop_column('location')
        batch_op.drop_column('branch')
        batch_op.drop_column('phone_number')

    with op.batch_alter_table('job_post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_post_user_id'))
        batch_op.drop_index(batch_op.f('ix_job_post_last_apply_date'))

    op.drop_table('job_post')
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donations_user_id'))
        batch_op.drop_index(batch_op.f('ix_donations_donation_time'))
        batch_op.drop_index(batch_op.f('ix_donations_ammount'))

    op.drop_table('donations')
    # ### end Alembic commands ###
